### ISSUE TITLE
tss2 tools test failing memory leak (3.2.x)

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#2470]
@JuergenReppSIT looks like the update caused a leak, i think its from commit e8741010:
```
Direct leak of 60 byte(s) in 1 object(s) allocated from:
    #0 0x493f8d in malloc (/workspace/tpm2-tools/build/tools/fapi/tss2+0x493f8d)
    #1 0x7f10f64d76b9 in ifapi_json_UINT8_ARY_deserialize /workspace/tpm2-tss/src/tss2-fapi/tpm_json_deserialize.c:344:19
    #2 0x7f10f6495a57 in ifapi_json_IFAPI_NV_deserialize /workspace/tpm2-tss/src/tss2-fapi/ifapi_json_deserialize.c:438:9
    #3 0x7f10f6497373 in ifapi_json_IFAPI_OBJECT_deserialize /workspace/tpm2-tss/src/tss2-fapi/ifapi_json_deserialize.c:694:13
    #4 0x7f10f64a4607 in ifapi_keystore_load_finish /workspace/tpm2-tss/src/tss2-fapi/ifapi_keystore.c:633:9
    #5 0x7f10f64b3aa7 in ifapi_policyeval_cbauth /workspace/tpm2-tss/src/tss2-fapi/ifapi_policy_callbacks.c:500:13
    #6 0x7f10f64bdbc2 in execute_policy_authorize_nv /workspace/tpm2-tss/src/tss2-fapi/ifapi_policy_execute.c:786:13
    #7 0x7f10f64b9906 in execute_policy_element /workspace/tpm2-tss/src/tss2-fapi/ifapi_policy_execute.c:1550:13
    #8 0x7f10f64b9257 in ifapi_policyeval_execute /workspace/tpm2-tss/src/tss2-fapi/ifapi_policy_execute.c:1765:13
    #9 0x7f10f64d3097 in ifapi_policyutil_execute /workspace/tpm2-tss/src/tss2-fapi/ifapi_policyutil_execute.c:290:17
    #10 0x7f10f6466425 in ifapi_authorize_object /workspace/tpm2-tss/src/tss2-fapi/fapi_util.c:2[148](https://github.com/williamcroberts/tpm2-tools/actions/runs/3413026788/jobs/5679263856#step:4:149):17
    #11 0x7f10f646facb in ifapi_key_sign /workspace/tpm2-tss/src/tss2-fapi/fapi_util.c:2856:13
    #12 0x7f10f64570b9 in Fapi_Sign_Finish /workspace/tpm2-tss/src/tss2-fapi/api/Fapi_Sign.c:294:17
    #13 0x7f10f6456475 in Fapi_Sign /workspace/tpm2-tss/src/tss2-fapi/api/Fapi_Sign.c:122:13
    #14 0x4c5797 in tss2_tool_onrun /workspace/tpm2-tools/build/../tools/fapi/tss2_sign.c:103:9
    #15 0x4be9e7 in main /workspace/tpm2-tools/build/../tools/fapi/tss2_template.c:552:11
    #16 0x7f10f4432bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
```
See PR:
  - [ifapi_authorize_object](https://github.com/williamcroberts/tpm2-tools/actions/runs/3413026788/jobs/5679263856)

Looks like this will also affect 3.2.x as commit 07b9eac71

**Comment by williamcroberts** [comment]
Fixed in #2471
