### ISSUE TITLE
FAIL test/unit/tcti-spi-ftdi

### ISSUE THREAD

**Issue by JuergenReppSIT** [tpm2-software/tpm2-tss#2610]
The unit test  test/unit/tcti-spi-ftdi produces an error after PR  #2549:
 tcti_spi_helper_transmit: ensure FIFO is accessed only after TPM repo…
was merged.
```
023-05-02T09:07:06.1589576Z FAIL: test/unit/tcti-spi-ftdi
2023-05-02T09:07:06.1589793Z =============================
2023-05-02T09:07:06.1590014Z
2023-05-02T09:07:06.1590095Z [==========] Running 1 test(s).
2023-05-02T09:07:06.1590353Z [ RUN      ] tcti_spi_no_wait_state_success_test
2023-05-02T09:07:06.1590659Z [  ERROR   ] --- 0xa0009 != 0
2023-05-02T09:07:06.1591023Z [   LINE   ] --- ../test/unit/tcti-spi-ftdi.c:178: error: Failure!
2023-05-02T09:07:06.1591387Z [  FAILED  ] tcti_spi_no_wait_state_success_test
2023-05-02T09:07:06.1591638Z [==========] 1 test(s) run.
2023-05-02T09:07:06.1591859Z [  PASSED  ] 0 test(s).
2023-05-02T09:07:06.1592097Z [  FAILED  ] 1 test(s), listed below:
2023-05-02T09:07:06.1592354Z [  FAILED  ] tcti_spi_no_wait_state_success_test
2023-05-02T09:07:06.1592516Z
2023-05-02T09:07:06.1592601Z  1 FAILED TEST(S)
```

**Comment by wxleong** [comment]
Where did you encounter this error? The CI passed, and the change in #2549 shouldn't affect the unit test since the function `tcti_spi_helper_transmit()` is actually a miss in the test (The code coverage for tcti-spi-helper is currently quite low, I will need to improve it).

**Comment by JuergenReppSIT** [comment]
Seems to be a problem with mbedtls and not with the test tcti-spi-ftdi

**Comment by JuergenReppSIT** [comment]
@wxleong There seems to be a race condition in this unit test. Now an error occured in openssuse leap gcc test. After restarting the test in the CI there was no error.
```
AIL: test/unit/tcti-spi-ftdi
2023-06-06T22:42:05.9548814Z =============================
2023-06-06T22:42:05.9549370Z
2023-06-06T22:42:05.9549611Z [==========] Running 1 test(s).
2023-06-06T22:42:05.9550198Z [ RUN      ] tcti_spi_no_wait_state_success_test
2023-06-06T22:42:05.9550646Z [  ERROR   ] --- 0xa0009 != 0
2023-06-06T22:42:05.9551340Z [   LINE   ] --- ../test/unit/tcti-spi-ftdi.c:178: error: Failure!
2023-06-06T22:42:05.9551801Z [  FAILED  ] tcti_spi_no_wait_state_success_test
2023-06-06T22:42:05.9552381Z [==========] 1 test(s) run.
2023-06-06T22:42:05.9552748Z [  PASSED  ] 0 test(s).
2023-06-06T22:42:05.9553498Z [  FAILED  ] 1 test(s), listed below:
2023-06-06T22:42:05.9553951Z [  FAILED  ] tcti_spi_no_wait_state_success_test
2023-06-06T22:42:05.9554177Z
2023-06-06T22:42:05.9554324Z  1 FAILED TEST(S)
2023-06-06T22:42:05.9554515Z
2023-06-06T22:42:05.9554679Z =================================================================
2023-06-06T22:42:05.9565224Z ==133755==ERROR: LeakSanitizer: detected memory leaks
2023-06-06T22:42:05.9565572Z
2023-06-06T22:42:05.9565778Z Direct leak of 168 byte(s) in 1 object(s) allocated from:
2023-06-06T22:42:05.9566210Z     #0 0x7fb0f1a332e8 in __interceptor_calloc (/usr/lib64/libasan.so.4+0xdc2e8)
2023-06-06T22:42:05.9566806Z     #1 0x401969 in tcti_spi_no_wait_state_success_test ../test/unit/tcti-spi-ftdi.c:173
2023-06-06T22:42:05.9567207Z     #2 0x7fb0f1750d98  (/usr/lib64/libcmocka.so.0+0x4d98)
2023-06-06T22:42:05.9567439Z
2023-06-06T22:42:05.9567641Z Indirect leak of 24 byte(s) in 1 object(s) allocated from:
2023-06-06T22:42:05.9568293Z     #0 0x7fb0f1a33110 in malloc (/usr/lib64/libasan.so.4+0xdc110)
2023-06-06T22:42:05.9568793Z     #1 0x402845 in create_tcti_spi_ftdi_platform ../src/tss2-tcti/tcti-spi-ftdi.c:144
2023-06-06T22:42:05.9569294Z     #2 0x402da1 in Tss2_Tcti_Spi_Ftdi_Init ../src/tss2-tcti/tcti-spi-ftdi.c:185
2023-06-06T22:42:05.9569819Z     #3 0x4019ad in tcti_spi_no_wait_state_success_test ../test/unit/tcti-spi-ftdi.c:177
2023-06-06T22:42:05.9570211Z     #4 0x7fb0f1750d98  (/usr/lib64/libcmocka.so.0+0x4d98)
```

**Comment by wxleong** [comment]
ok, I'll check on it
