### ISSUE TITLE
Fapi_Import crashes with SIGSEGV when importing a policy that contains "null" element

### ISSUE THREAD

**Issue by dEajL3kA** [tpm2-software/tpm2-tss#2878]
For example, importing this policy with `Fapi_Import()` triggers a SIGSEGV for me:
```
{
  "description": "Description pol_duplicate",
  "policy": [
    {
      "type": "POLICYDUPLICATIONSELECT",
      "newParentPath": null
    }
  ]
}
```

Stack trace:
```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
#1  0x00007f4d5ca888de in __GI___strdup (s=0x0) at ./string/strdup.c:41
#2  0x00007f4d5cd22a11 in ?? () from /lib/x86_64-linux-gnu/libtss2-fapi.so.1
#3  0x00007f4d5cd3e765 in ?? () from /lib/x86_64-linux-gnu/libtss2-fapi.so.1
#4  0x00007f4d5cd419fc in ?? () from /lib/x86_64-linux-gnu/libtss2-fapi.so.1
#5  0x00007f4d5cd40cc4 in ?? () from /lib/x86_64-linux-gnu/libtss2-fapi.so.1
#6  0x00007f4d5cd41d25 in ?? () from /lib/x86_64-linux-gnu/libtss2-fapi.so.1
#7  0x00007f4d5cced0b9 in Fapi_Import_Async () from /lib/x86_64-linux-gnu/libtss2-fapi.so.1
#8  0x00007f4d5ccef114 in Fapi_Import () from /lib/x86_64-linux-gnu/libtss2-fapi.so.1
[...]
#19 0x00007f4d5ca73134 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
```

Tested on Debian Bookworm as well as on Sid/Trixie, both with the "built-in" version of `libtss2-fapi1`.

I know that this is an *invalid* input, but it shouldn't cause the FAPI to crash, I suppose 😏

**Comment by dEajL3kA** [comment]
Closing, as fix seems to be in the way. Thanks.
